CREATE TABLE DECKS (
	deckID      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	deckName    VARCHAR(255) NOT NULL,
	creationDate DATE DEFAULT CURRENT_DATE NOT NULL
);

CREATE TABLE CARDS (
	cardID      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	cardType    VARCHAR(10) NOT NULL CHECK (cardType IN ('BASIC', 'IMAGE')),
	createdDate DATE DEFAULT CURRENT_DATE NOT NULL
);

CREATE TABLE CARD_STATS(
	cardID BIGINT PRIMARY KEY,
	isNewCard BOOLEAN DEFAULT TRUE,
	isHard BOOLEAN DEFAULT FALSE,
	delayOffset INT DEFAULT 0,
	CONSTRAINT card_stats_fk FOREIGN KEY (cardID) REFERENCES CARDS(cardID) ON DELETE CASCADE
);

CREATE TABLE BASIC_CARDS (
	cardID      BIGINT PRIMARY KEY,
	frontSide   VARCHAR(255) NOT NULL,
	backSide    VARCHAR(255) NOT NULL,
	CONSTRAINT basic_card_fk FOREIGN KEY (cardID) REFERENCES CARDS(cardID) ON DELETE CASCADE,
	CONSTRAINT basic_unique_content UNIQUE (frontSide, backSide)
);

CREATE TABLE IMAGE_CARDS (
	cardID      BIGINT PRIMARY KEY,
	answerText   VARCHAR(255) NOT NULL,
	imagePath   VARCHAR(500) NOT NULL,
	CONSTRAINT image_card_fk FOREIGN KEY (cardID) REFERENCES CARDS(cardID) ON DELETE CASCADE,
	CONSTRAINT image_unique_content UNIQUE (answerText, imagePath)
);

CREATE TABLE DECKS_TO_CARDS(
	deckID BIGINT,
	cardID BIGINT,
	constraint decks_to_cards_pk PRIMARY KEY (deckID, cardID),
	constraint deck_ID_fk FOREIGN KEY (deckID) REFERENCES DECKS(deckID) ON DELETE CASCADE,
	constraint card_ID_fk FOREIGN KEY (cardID) REFERENCES CARDS(cardID) ON DELETE CASCADE
);
